version: "3.9"

services:
  blog:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./myFirstBlog/:/usr/src/myFirstBlog/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    # depends_on:
    #   - db
  postgresql:
    image: postgres:12.0-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=blogdb
      - POSTGRES_PASSWORD=blogdb

volumes:
    postgresql_data: {}
# docker run -d -e POSTGRES_PASSWORD=blogdb -e POSTGRES_USER=blogdb -e POSTGRES_DB=blogdb -p 5432:5432 postgres:12.0-alpine
# backup
# docker exec -t myfirstblog_postgresql_1 pg_dumpall -c -U blogdb > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
# restore
# cat dump_16-01-2021_22_58_21.sql | docker exec -i myfirstblog_postgresql_1 psql -U blogdb
