version: "3.9"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile.prd
    command: gunicorn myFirstBlog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/myFirstBlog/myFirstBlog/static
      - media_volume:/home/app/myFirstBlog/myFirstBlog/media
    expose:
      - 8000
    env_file:
      - ./.env.prd
    depends_on: 
      - postgresql
  postgresql:
    image: postgres:12.0-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prd.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/myFirstBlog/myFirstBlog/static
      - media_volume:/home/app/myFirstBlog/myFirstBlog/media
    ports:
      - 80:80
    depends_on:
      - blog

volumes:
    postgresql_data: {}
    static_volume: {}
    media_volume: {}