version: "3.9"

services:
  web:
    build: .
    command: gunicorn myFristBlog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./myFirstBlog/:/usr/src/myFirstBlog/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prd
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prd.db

volumes:
  postgres_data: