# Generated by Django 3.1.5 on 2021-01-16 15:49

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('body', markdownx.models.MarkdownxField()),
                ('background_image', models.ImageField(default='img/header.jpg', upload_to='backgrounds/2021/01/16')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
