# Generated by Django 3.1.5 on 2021-01-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20210117_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='background_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
