# Generated by Django 3.1.5 on 2021-01-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20210117_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(default='myBlog', max_length=50)),
                ('welcome_phrase', models.CharField(default='Welcome', max_length=200)),
                ('short_description', models.CharField(default='Description', max_length=200)),
                ('brief_intro', models.CharField(default='Hello', max_length=200)),
                ('social_url', models.CharField(default='www.example.com', max_length=50)),
            ],
        ),
    ]
