# Generated by Django 3.1.5 on 2021-01-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_genericconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericconfig',
            name='config_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='genericconfig',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
