# Generated by Django 3.1.5 on 2021-01-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_auto_20210117_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(default='media/error.png', upload_to='2021/01/22'),
        ),
    ]
