# Generated by Django 3.1.5 on 2021-01-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_auto_20210122_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image_name',
        ),
    ]
