# Generated by Django 3.1.5 on 2021-01-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_remove_uploadedimage_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='2021/01/24'),
        ),
    ]
