# Generated by Django 3.1.5 on 2021-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_auto_20210124_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericconfig',
            old_name='social_url',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='genericconfig',
            name='gmail_url',
            field=models.CharField(default='www.example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='genericconfig',
            name='linkedin_url',
            field=models.CharField(default='www.example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='genericconfig',
            name='skype_url',
            field=models.CharField(default='www.example.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='2021/01/26'),
        ),
    ]
